### ISSUE TITLE
Add `EmailEditor` to `EventView`

### ISSUE THREAD

**Issue by andlrutt** [hack4impact-utk/compassion-ministries#184]
### Description
Add email editor to event view :)

### Technical Details
- Add the `EmailEditor` component to the `EventView` component
- Add a "Send email to volunteers" button above the list of volunteers
- After clicking:
  - Display the `EmailEditor` component
  - Show a "Send" [button ](https://mui.com/material-ui/react-button/) ('contained' variant) on the bottom right 
    - After clicking send, display a popup confirming how many people this will send an email to
  - Confirmation should hide the `EmailEditor` component and send button
  - If #185 is complete, it should also send the emails

### Dependencies
- #183

**Comment by Frank-D-stein** [comment]
why is this still open
