### ISSUE TITLE
Research Google Calendar API

### ISSUE THREAD

**Issue by zaviermiller** [hack4impact-utk/compassion-ministries#2]
### Description
Research the google calendar API to see what options are available to us. It is in our PRD to create an event management system that can manage recurring events and edit specific ones in the future. If we don't have to reinvent the wheel, we don't want to.

### Technical Details
We are wanting to know:
- What APIs are available
- Is it a viable alternative to us creating an event management system from scratch
- What embedding a calendar on a webpage would look like in terms of creating, editing, and viewing recurring events
    - alternatively, solely using the calendar as a backend to manage things like which volunteers attended an event, which roles are at an event, and other event parameters
- If it's possible, think about how it could integrate with our system for things like tracking `EventVolunteer` documents per-event, reporting, event roles, and emails
- What are the costs associated with using the Google Calendar API?

### Dependencies
None

**Comment by andlrutt** [comment]
[Google Calendar API Research.docx](https://github.com/hack4impact-utk/compassion-ministries/files/13276027/Google.Calendar.API.Research.docx)
