### ISSUE TITLE
Create BGCIcon component

### ISSUE THREAD

**Issue by andlrutt** [hack4impact-utk/compassion-ministries#205]
### Description
Takes in a backgroundcheck object, and disaplys a check, red x, or yellow pending icon depending on the status of the background check

### Technical Details
- Use [this](https://mui.com/material-ui/material-icons/?query=check&selected=CheckCircle) for a passed background check
- Use [this](https://mui.com/material-ui/material-icons/?query=cross&selected=Cancel) for a failed background check
- Use [this](https://mui.com/material-ui/material-icons/?query=progress&selected=Pending) for a pending background check
- Match the icon size from the `<IconList>` component

**Comment by MattJacobs30** [comment]
Here is what the icons look like
![Image](https://github.com/hack4impact-utk/compassion-ministries/assets/144471849/aa4c8ea4-0cc8-4d3d-a7e9-92ce745e3479)
