### ISSUE TITLE
Volunteer Page Visual Fix

### ISSUE THREAD

**Issue by djwoun** [hack4impact-utk/compassion-ministries#260]
### Description
Perform a minor visual enhancement to the volunteer page

### Technical Details
Standardize the gap between "Address" and "Previous Organization" so it matches the spacing between the rest of the lines.

**Comment by ethanhmaness** [comment]
this looks like its already fixed on main

**Comment by djwoun** [comment]
![b81210483907e4b340758204aef44bc6](https://github.com/hack4impact-utk/compassion-ministries/assets/65102751/8cba93e7-b30e-4065-942d-f2f113ee758e)

**Comment by djwoun** [comment]
We want to try make the gap between Address and Previous Organization the same as Email and Phone Number
